language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'

os:
  - 'linux'
  - 'osx'
  - 'windows'
  #- 'freebsd'

notifications:
  email:
    - eoin.shanaghy@gmail.com
